### ISSUE TITLE
Decorating events assumes message field is a string

### ISSUE THREAD

**Issue by ralphm** [logstash-plugins/logstash-input-kafka#33]
When `decorate_events` is set to `true`, `msg_size` is set by [calling `bytesize`](https://github.com/logstash-plugins/logstash-input-kafka/blob/112692fe61c731bce19d7fd355bbc4d28c30d7dd/lib/logstash/inputs/kafka.rb#L166) on the event's `message` field. This assumes that this field is always a string, and fails if it is a hash instead, as in my particular use-case.

**Comment by joekiller** [comment]
Definitely a bug.  This will require jruby-kafka to be updated to pass
along the message and metadata object instead of just the message object as
it is currently doing (
https://github.com/joekiller/jruby-kafka/blob/master/lib/jruby-kafka/consumer.rb#L32)
then we can read the kafka message size from the metadata instead of
assuming the message itself is a string.  It'll require a new major version
of jruby-kafka as the fix won't be backwards compatible.

**Comment by jpodeszwik** [comment]
Isn't it already changed in jruby-kafka? I think we should change ```'msg_size' => event['message'].bytesize``` to something like ```'msg_size' => message_and_metadata.message.size``` [here](https://github.com/logstash-plugins/logstash-input-kafka/blob/112692fe61c731bce19d7fd355bbc4d28c30d7dd/lib/logstash/inputs/kafka.rb#L166).

**Comment by joekiller** [comment]
Your right, I was looking at the wrong line of my code so this should be a
pretty trivial fix.

**Comment by talevy** [comment]
From my understanding, this is in fact a bug. It is best to calculate the size of the message as it is stored in kafka via the MessageAndMetadata object. let me know what you think about the fix in #34. 

Thanks for submitting the issue!

**Comment by ralphm** [comment]
Looks good. Full message size makes sense to me.Thanks for the quick response!
