### ISSUE TITLE
Bump to Kafka client to 2.4.0

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#335]
This is a request to bump Kafka client to 2.4.0 (released in Dec 2019)

**Comment by ItamarBenjamin** [comment]
a more recent 2.4.1 version has been published

**Comment by yaauie** [comment]
The Kafka Integration Plugin, which moving forward is the source-of-truth for both the Kafka Input and Output plugins, has included Kafka client 2.4.x since [`v10.1.0`](https://github.com/logstash-plugins/logstash-integration-kafka/blob/master/CHANGELOG.md#1010).

The Integration Plugin runs on Logstash >= 6.5, and comes bundled with Logstash 7.5.
 - If you already have the integrated plugin installed, you can use the plugin manager to [update](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#updating-plugins) to the latest version.
 - If your Logstash has the individual input and output plugins installed, you may first have to [remove](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#removing-plugins) them before you can [install](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#installing-plugins) the combined integration plugin.
