### ISSUE TITLE
Support Kafka 0.9 consumer API for performance and security features

### ISSUE THREAD

**Issue by ppf2** [logstash-plugins/logstash-input-kafka#48]
It looks like we will be reworking the logstash-input-kafka to support upcoming Kafka 0.9 release that has performance improvements for the consumer.  This ticket is created to track our progress.

**Comment by talevy** [comment]
Kafka 0.9 has been released: http://www.confluent.io/blog/apache-kafka-0.9-is-released

**Comment by yohansson** [comment]
Definitely keen to see this implemented. Thanks.

**Comment by felipegs** [comment]
+1

**Comment by debraj-manna** [comment]
How is logstash supposed to behave with Kafka's [quota](http://kafka.apache.org/090/documentation.html#design_quotas) introduced in Kafka 0.9? 

Let's say a single instance of logstash is pushing logs from two different services (logs are pushed via logstash-forwarder) to kafka with clientIds `A` & `B` respectively. `Client A` is sending data under its quota while `Client B` is exceeding its quota. Since `client B` violates the quota as configured in Kafka then Kafka will delay the response to slow down `B` to bring its usage under quota. This will in turn exert a back-pressure on the logstash-forwarder & slow its log forwarding to logstash. 

Due to this slow down:-

1. Will the logstash-forwarder, who is forwarding logs for `Client A` (who is not violating the quota ) be effected in anyway or
2. The slow down of logstash will effect both `Client A` & `Client B` or
3. This will slow down all logstash outputs not just restricted to Kafka Outputs

**Comment by devnal** [comment]
+1

**Comment by joekiller** [comment]
Just an FYI the 0.9 consumer is considered beta (http://kafka.apache.org/documentation.html#consumerapi) so we may want make it a toggle.

**Comment by joekiller** [comment]
FYI 0.9.0.1 is in the works. http://mail-archives.apache.org/mod_mbox/kafka-users/201602.mbox/browser

**Comment by Roguelazer** [comment]
+1 I am also interested in this. I'm hoping it'll fix the periodic hangs I see with the current logstash-input-kafka against a kafka 0.9 cluster.

**Comment by joekiller** [comment]
@roguelazer are you running the cluster in 0.8 mode? Could you describe the hang you are encountering and frequency of the occurrence? Any telling loh messages on Logstash, Kafka broker or zookeeper?

**Comment by joekiller** [comment]
Loh = log. Durn smartphone.

**Comment by Roguelazer** [comment]
@joekiller 

I have some logstashes which have only a single instance reading from a topic and still will die with a `"kafka.common.ConsumerRebalanceFailedException: logstash-ksrv_hostname-1456506389688-82c48305 can't rebalance after 15 retries"` every few hours. Once they get that exception, the process seems to hang; `jstack <pid>` won't attach, and `jstack -F <pid>` dies with:

    Deadlock Detection:
    
    java.lang.RuntimeException: Unable to deduce type of thread from address 0x00007f8f5c664000 (expected type JavaThread, CompilerThread, ServiceThread, JvmtiAgentThread, or SurrogateLockerThread)

I know that they rewrote the rebalancing logic in the 0.9 consumer, so I'm hopeful that this issue will go away at that point.

Restarting logstash always fixes the problem (to the point where I've added a cron job to restart it every 3 hours).

Let me know if you want me to file that as a separate issue (either here or in JRuby-Kafka).

**Comment by owulff** [comment]
+1
Key feature for us to protect the data in the cluster from being consumed by untrusted parties.

**Comment by pcallewaert** [comment]
+1

**Comment by andreicristianpetcu** [comment]
I see jruby-kafka has a new version that works with TLS. Does this help? https://github.com/joekiller/jruby-kafka/issues/40#issuecomment-172566550

**Comment by joekiller** [comment]
Try building the 0.9 branch. https://github.com/logstash-plugins/logstash-input-kafka/tree/update/0.9

**Comment by shaharmor** [comment]
Hey guys, any update on this?

**Comment by raviv** [comment]
Hi, I'm using beta 4 and it ignores the "tags" and "add_field" param. Thanks!

**Comment by talevy** [comment]
@shaharmor kafka 0.9 support can be found in the `3.0.0.beta4` release of the plugin. This is now packaged within Logstash 5.0-alpha1. You can manually update if you want to try it out! but there is still some work to be done in it (that is why it is beta).

**Comment by talevy** [comment]
this was just pushed to rubygems by @suyograo.

https://rubygems.org/gems/logstash-input-kafka/versions/3.0.2

version 3.0.2 now supports this
